pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = "petarmc"
            url = "https://repo.petarmc.com/repository/maven-public/"
        }
        gradlePluginPortal()
    }
}
rootProject.name = 'FishTracker'